piro20_Ajax_Pirostagram/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
]

piro20_Ajax_Pirostagram/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post_new/', views.post_new, name='post_new'),
    path('like_ajax/', views.like_ajax, name = 'like_ajax'),
    path('delete_comment/', views.delete_comment, name = 'delete_comment'),
    path('create_comment/', views.create_comment, name = 'create_comment')
]

piro20_Ajax_Pirostagram/users/urls.py
# users/urls.py -> 직접 생성
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("signup/", views.signup, name="signup"),
]

piro20_Ajax_Pirostagram/main/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

class PostLike(models.Model):
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment')

piro20_Ajax_Pirostagram/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    name = models.CharField('이름', max_length=20, unique=True)
    
    def __str__(self):
        return self.name

piro20_Ajax_Pirostagram/main/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

piro20_Ajax_Pirostagram/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignupForm(UserCreationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
   
    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class' : 'signup-input'
            }
        )
    )
    
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'name',]

piro20_Ajax_Pirostagram/main/views.py
from django.shortcuts import render, redirect
from .models import Post, PostLike, Comment
from .forms import PostForm

# Create your views here.


def post_list(request):
    posts = Post.objects.all()
    ctx = {
        'posts': posts,
    }
    return render(request, 'main/post_list.html', ctx)


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main:post_list')
        else:
            ctx = {
                'form': form,
            }
            return render(request, 'main/post_new.html', ctx)
    elif request.method == 'GET':
        form = PostForm()
        ctx = {
            'form': form,
        }
        return render(request, 'main/post_new.html', ctx)
    
import json
from django.http import JsonResponse 
from django.views.decorators.csrf import csrf_exempt 

@csrf_exempt
def create_comment(request):  
    req = json.loads(request.body)
    post_id = req['id']
    comment_content = req['comment_content']
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.create(content=comment_content, user=request.user, post=post)
    return JsonResponse({'post_id': post_id, 'comment': comment_content, 'user': comment.user.name, 'comment_id': comment.pk})

@csrf_exempt
def delete_comment(request):
    req = json.loads(request.body)
    comment_id = req['id']
    comment = Comment.objects.get(id=comment_id)          
    comment.delete()
    return JsonResponse({'comment_id': comment_id})
        
@csrf_exempt
def like_ajax(request):
    req = json.loads(request.body)
    post_id = req['id']
    post = Post.objects.get(id=post_id)

    like_objects = PostLike.objects.filter(post=post, user=request.user)
    if like_objects.exists():
        like_objects.delete()
        result = 'like removed'
    else:
        PostLike.objects.create(post=post, user=request.user)
        result = 'like added'

    return JsonResponse({"id": post_id, "result": result})

piro20_Ajax_Pirostagram/users/views.py
from django.shortcuts import render, redirect
from users.forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)
            return redirect('/')
        else:
            ctx={
                'form':form,
            }
            return render(request, 'users/signup.html',context=ctx) # 이부분 수정
    else:
        form = SignupForm()
        context={
            'form': form,
        }
        return render(request, template_name='users/signup.html', context=context)
    
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('/')
        else:
            context = {
                'form': form,
            }
            return render(request, template_name='users/login.html', context=context)
    else:
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, template_name='users/login.html', context=context)


def logout(request):
    auth.logout(request)
    return redirect('/')

piro20_Ajax_Pirostagram/config/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajax-lecture</title>

    {% block extra_head %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'layout.css' %}">
    {% endblock %}
</head>
<body>
    <header>
        <div class="header__container">
            <div class="header__text">
                ✨ Pirostargram ✨
            </div>
            <div class="nav">
                {% if user.is_authenticated %}
                    <a href="{% url 'main:post_new' %}" class="top-menu"><i class="fa-solid fa-pencil"></i><span>새 게시물 쓰기</span></a>
                {% endif %}
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'users:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                        <li><a href="{% url 'users:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>
    
    {% block content %}
        <!-- 기본 내용 -->
    {% endblock %}

    {% block extra %}
    {% endblock %}
</body>
</html>

piro20_Ajax_Pirostagram/main/templates/main/post_list.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div class="main__container">
        {% for post in posts %}
            <div class="card post__container post-id-{{ post.id }}">
                <div class="card-body">
                    <div class="post__img">
                        <img src="{% static 'img/img_lights.jpg' %}" alt="...">
                    </div>
                    <div class="card-title">{{ post.title }}</div>
                    <div class="card-text">{{ post.content}}</div>
                    <div class="btn btn-primary post-like" onclick=" onClickLike({{ post.id }})">Like {{ post.likes.count }}</div>
                    
                    <div id="commentinput">
                        <input type="text" id="commentInput-{{ post.id }}" placeholder="댓글 남기기" required>
                        <button input-id="{{ post.id }}">댓글 달기</button>
                    </div>
                    
                    <div id="commentList-{{post.id}}">
                        {% for comment in post.comment.all %}
                        <div class="comment" id="comment-{{ comment.id }}">
                            {{ comment.user.name }}: {{ comment.content }}
                            <button onclick="deleteComment({{ comment.id }});">댓글 삭제</button>
                        </div>
                        {% endfor %}
                    </div>
                    
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block extra %}
<script>
    const requestCreateComment = new XMLHttpRequest();

    const createComment = (postId) => {
        const commentContent = document.getElementById(`commentInput-${postId}`).value;
        const url = "/create_comment/";
        requestCreateComment.open("POST", url, true);
        requestCreateComment.setRequestHeader(
            "Content-Type", 
            "application/x-www-form-urlencoded");
        requestCreateComment.send(JSON.stringify({ id: postId , comment_content : commentContent}));
    }

    requestCreateComment.onreadystatechange = () => {
        if (requestCreateComment.readyState == XMLHttpRequest.DONE) {
            if (requestCreateComment.status < 400) {
                const { post_id, comment, user, comment_id } = JSON.parse(requestCreateComment.response);
                const commentList = document.getElementById(`commentList-${post_id}`);
                
                const newComment = document.createElement("div");
                newComment.className = "comment"
                newComment.id = `comment-${ comment_id }`
                newComment.innerHTML = `
                    ${user}: ${comment}
                    <button onclick="deleteComment(${ comment_id });">댓글 삭제</button>
                    `;
                commentList.appendChild(newComment);
            } 
        }
    }

    document.querySelectorAll('[input-id]').forEach(function(button) {
        button.addEventListener('click', function() {
            const postId = this.getAttribute('input-id');
            createComment(postId);
        }); 
    });
   
    const requestDeleteComment = new XMLHttpRequest();

    const deleteComment = (commentId) => {
        const url = "/delete_comment/";
        requestDeleteComment.open("POST", url, true);
        requestDeleteComment.setRequestHeader(
            "Content-Type", 
        "application/x-www-form-urlencoded");
        requestDeleteComment.send(JSON.stringify({ id: commentId }));
    }

    requestDeleteComment.onreadystatechange = () => {
        if (requestDeleteComment.readyState == XMLHttpRequest.DONE) {
            if (requestDeleteComment.status < 400) {
                const { comment_id } = JSON.parse(requestDeleteComment.response);
                const commentToDelete = document.getElementById(`comment-${comment_id}`);
                if (commentToDelete) {
                    commentToDelete.parentNode.removeChild(commentToDelete);
                }
            }
        }
    }

    const requestLike = new XMLHttpRequest();

    const onClickLike = (id) => {
        const url = "/like_ajax/";
        requestLike.open("POST", url, true);
        requestLike.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({id : id}));
    }

    requestLike.onreadystatechange = () => {
        if (requestLike.readyState == XMLHttpRequest.DONE){
            if(requestLike.status < 400 ){
                const{id,result} = JSON.parse(requestLike.response);
                const element = document.querySelector(`.post-id-${id} .post-like`);
                const originHTML = element.innerHTML;
                const [buttonType, num] = originHTML.split(" ");
                let count;
                if(result == 'like added')
                    count = Number(num) + 1;
                else
                    count = Number(num) - 1;
                element.innerHTML = `${buttonType} ${count}`;
            }
        }
    }
</script> 
{% endblock %}

piro20_Ajax_Pirostagram/main/templates/main/post_new.html
{% extends 'layout.html' %}
{% load static %}

{% block content %}
    <div class="form__container">
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>

            <input type="submit" value="submit">
        </form>
    </div>
{% endblock %}

piro20_Ajax_Pirostagram/users/templates/users/login.html
{% extends 'layout.html' %}

{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form }}
    <button>Login</button>
</form>
{% endblock content %}

piro20_Ajax_Pirostagram/users/templates/users/signup.html
{% extends 'layout.html' %}

{% block content %}
<div class="Flex_cc">
    <form method="POST" action="" id="signup1">
        {% csrf_token %}
        {{ form }}
        <div class="container">
            <input class="signup1-btn nice-effect" type="submit" value="회원가입">
            <div class="overlay"></div>
        </div>
    </form>
</div>
{% endblock content %}