SWIDEA_SITE/apps/devtools/urls.py
from django.urls import path
from .views import *

app_name = 'devtools'

urlpatterns = [
    path('list', devtools_list, name = 'list'),
    path('create/', devtool_create, name = 'create'),
    path('delete/<int:pk>/',devtool_delete,name = 'delete'),
    path('detail/<int:pk>/',devtool_detail, name = 'detail'),
    path('update/<int:pk>/', devtool_update, name = 'update'),
]

SWIDEA_SITE/apps/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
    path('', ideas_list, name = 'list'),
    path('create/', ideas_create, name = 'create'),
    path('detail/<int:pk>/', idea_detail , name = 'detail'),
    path('delete/<int:pk>/',idea_delete, name = 'delete'),
    path('update/<int:pk>/', idea_update, name = 'update'),
]

SWIDEA_SITE/swidea_site/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.ideas.urls')),
    path('devtools/', include('apps.devtools.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/apps/devtools/models.py
from django.db import models

# Create your models here.
class DevTool(models.Model):
    name = models.CharField(max_length = 100)
    kind = models.CharField(max_length = 30)
    content = models.TextField()
    def __str__(self):
        return self.name

SWIDEA_SITE/apps/ideas/models.py
from django.db import models

from apps.devtools.models import DevTool


class Idea(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField('이미지', blank=True, upload_to='ideas/%Y%m%d')
    content = models.TextField()
    interest = models.IntegerField()
    devtool = models.ForeignKey(DevTool, on_delete = models.CASCADE, verbose_name= '개발툴')

class Like(models.Model):
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)  # YourItemModel을 실제 모델로 교체

SWIDEA_SITE/apps/devtools/forms.py
from django import forms
from .models import DevTool

class DevToolForm(forms.ModelForm):
    class Meta():
        model = DevTool
        fields = ('__all__')
        labels = {
            'name': '개발툴 이름',
            'kind': '종류',
            'content': '내용'
        }

SWIDEA_SITE/apps/ideas/forms.py
from django import forms
from .models import Idea

class IdeaForm(forms.ModelForm):
    class Meta():
        model = Idea
        fields = ('__all__')
        labels = {
            'title': '아이디어 제목',
            'image': '사진',
            'content': '내용',
            'interest' : '관심도'
        }

SWIDEA_SITE/apps/devtools/views.py
from django.shortcuts import render, redirect
from .models import DevTool
from .forms import *

def devtools_list(request):
    devtools = DevTool.objects.all() 
    return render(request, 'devtools/devtools_list.html', {'devtools' : devtools })

def devtool_create(request):
    if request.method == 'GET':
        form = DevToolForm()
        ctx = {'form' : form}
        return render(request, 'devtools/devtool_create.html', ctx)
    form = DevToolForm(request.POST, request.FILES)
    if form.is_valid():
        form = form.save()
    return redirect('devtools:detail', form.id)


def devtool_detail(request, pk):
    devtool = DevTool.objects.get(id = pk)
    related_ideas = devtool.idea_set.all()
    ctx = {'devtool' : devtool , 'related_ideas' : related_ideas}
    return render(request, 'devtools/devtool_detail.html', ctx)

 
def devtool_update(request, pk):
    devtool = DevTool.objects.get(id = pk)
    if request.method == 'GET':
        form = DevToolForm(instance=devtool)
        ctx = {'form' : form, "pk" : pk}
        return render(request, 'devtools/devtool_update.html', ctx)
    form = DevToolForm(request.POST, request.FILES, instance=devtool)
    
    if form.is_valid():      
        form.save()
    return redirect('devtools:detail', pk)

def devtool_delete(request, pk):
    if request.method == 'POST':
        DevTool.objects.get(id = pk).delete()
    return redirect('devtools:list')

SWIDEA_SITE/apps/ideas/views.py
from django.shortcuts import render, redirect
from .models import Idea, Like
from django.http import JsonResponse
from .forms import *

def ideas_list(request):
    if request.method == 'POST':
        sort_option = request.POST.get('sort_option')
        ideas = Idea.objects.all().order_by(sort_option)
        return render(request, 'ideas/ideas_list.html', {'ideas': ideas})
    
    ideas = Idea.objects.all().order_by('id')
    return render(request, 'ideas/ideas_list.html',  {'ideas': ideas})


def ideas_create(request):
    if request.method == 'GET':
        form = IdeaForm()
        ctx = {'form' : form}
        return render(request, 'ideas/idea_create.html', ctx)
    
    form = IdeaForm(request.POST, request.FILES)
    
    if form.is_valid():
        form = form.save()
    return redirect('ideas:detail', form.id)

def idea_detail(request, pk):
    idea = Idea.objects.get(id = pk)
    ctx = {'idea' : idea}
    return render(request, 'ideas/idea_detail.html', ctx)

def idea_delete(request, pk):
    if request.method == 'POST':
        Idea.objects.get(id = pk).delete()
    return redirect('/')

def idea_update(request, pk):
    idea = Idea.objects.get(id = pk)
    if request.method == 'GET':
        form = IdeaForm(instance=idea)
        ctx = {'form' : form, "pk" : pk}
        return render(request, 'ideas/idea_update.html', ctx)
    form =IdeaForm(request.POST, request.FILES, instance=idea)
    
    if form.is_valid():      
        form.save()
    return redirect('ideas:detail', pk)

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'css/style.css'%}">  
    <title>Document</title>
</head>
<body>
    <header class="header">
        <div class="logo">
            <a href="{% url 'ideas:list' %}">My SW idea manager</a>
        </div>
        <nav class="header_nav">
            <ul>
                <li><a href="{% url 'ideas:create' %}" class="nav_li">아이디어 등록</a></li>
                <li><a href="{% url 'ideas:list' %}" class="nav_li">아이디어 관리</a></li>
                <li><a href="{% url 'devtools:create' %}" class="nav_li">개발툴 등록</a></li>
                <li><a href="{% url 'devtools:list' %}" class="nav_li">개발툴 관리</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container">
            <div class = "main_header">
                {%block header%}

                {%endblock%}
            </div>
            {%block content%}

            {%endblock%}
        </div>       
    </main>
</body>
</html>

SWIDEA_SITE/templates/devtools/devtool_create.html
{% extends 'base.html' %}


{%block header%}
    <h2>개발툴 등록</h2>
    <p>개발툴을 등록하세요</p>
{%endblock%}

{%block content%}
  <div class="form">
    <form action="{% url 'devtools:create' %}" method="post">
      {%csrf_token%} 
      {{form.as_p}}
      <button class="btn btn-success">등록하기</button>
    </form>
  </div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_detail.html
{% extends 'base.html' %}


{%block header%}
    <h2>개발툴 상세페이지</h2>
    <p>개발툴 상세페이지입니다</p>
{%endblock%}

{%block content%}
    <div class="detail">
        <div class="detail_main">
            <div class="detail_info">
                <h1>{{devtool.name}}</h1>
                <p>{{devtool.kind}}</p>
                <p>{{devtool.content}}</p>
                <div class="relate">
                    <h3>이 개발 툴을 사용하는 아이디어들</h3>
                    {% for idea in related_ideas %}
                        <a href="{% url 'ideas:detail' idea.pk %}">
                        {{idea.title}}
                        </a>
                    {% endfor %}
                </div>
            </div>
            
        </div>

        <div class="buttons">
            <form action="{% url 'devtools:delete' devtool.pk %}" method="POST">
                {%csrf_token%}
                <button type="submit" href="{% url 'devtools:delete' devtool.pk %}" class="btn_del">삭제하기</button>
            </form>
            
            <a href="{% url 'devtools:list' %}"> 목록 </a>
            
            <form action="{% url 'devtools:update' devtool.pk %}" method="POST">
                {%csrf_token%}
            <a href="{% url 'devtools:update' devtool.pk %}" class="btn btn-primary">수정하기</a>
            </form>
        </div>
    </div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtool_update.html
{% extends 'base.html' %}


{%block header%}
    <h2>개발툴 수정</h2>
    <p>개발툴을 수정하세요</p>
{%endblock%}

{%block content%}
<div class="form">
  <form action="{% url 'devtools:update' pk %}" method="post">
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/devtools/devtools_list.html
{% extends 'base.html' %}


{%block header%}
    <h2>개발툴 리스트</h2>
    <p>개발툴을 관리하세요</p>
{%endblock%}

{%block content%}
  <div class="col_list">
    {% for devtool in devtools %}
      <div class = "dev_list_li">
        <a href = "{% url 'devtools:detail' devtool.pk%}" class="title"> {{devtool.name}}</a>
        <span class = "devtool_kind">{{devtool.kind}}</span>
        <span class = "devtool_content">{{devtool.content}}</span>
      </div>
    {% endfor %}
  </div>
{%endblock%} 

SWIDEA_SITE/templates/ideas/idea_create.html
{% extends 'base.html' %}


{%block header%}
    <h2>아이디어 등록</h2>
    <p>당신의 아이디어를 등록하세요</p>
{%endblock%}


{%block content%}
<div class="form">
  <form action="{% url 'ideas:create' %}" method="post" enctype="multipart/form-data">
    {%csrf_token%} 
    {{form.as_p}}
    <button class="btn btn-success">등록하기</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_detail.html
{% extends 'base.html' %}
{% load static %}

{%block header%}
    <h2>아이디어 상세페이지</h2>
    <p>아이디어 상세 페이지입니다</p>
{%endblock%}

{%block content%}
    <div class="detail">
        <div class="detail_main">
            {% if idea.image.url != '' %}
                <img src="{{idea.image.url}}" alt="이미지" />
            {% else %}
                <img src="{% static 'ideas/image/no_img.png' %}" alt="대체 텍스트" />
            {% endif %}
            <div class="detail_info">
                <h1>{{idea.title}}</h1>
                <p>1. 관심도 : {{idea.interest}}</p>
                <a href="{% url 'devtools:detail' idea.devtool.id %}">2. 개발 툴 : {{idea.devtool}}</ㅁ>
                <p>3. 내용 : {{idea.content}}</p>
            </div>
        </div>
        <div class="buttons">
            <form action="{% url 'ideas:delete' idea.pk %}" method="POST">
                {%csrf_token%}
                <button type="submit" href="{% url 'ideas:delete' idea.pk %}" class="btn_del">삭제하기</button>
            </form>

            <a href="{% url 'ideas:list' %}"> 목록 </a>
            <form action="{% url 'ideas:update' idea.pk %}" method="POST">
                {%csrf_token%}
            <a href="{% url 'ideas:update' idea.pk %}">수정하기</a>
            </form>
        </div>
    </div>
{%endblock%}

SWIDEA_SITE/templates/ideas/idea_update.html
{% extends 'base.html' %}


{%block header%}
    <h2>아이디어 수정</h2>
    <p>당신의 아이디어를 수정하세요</p>
{%endblock%}

{%block content%}
<div class="form">
  <form action="{% url 'ideas:update' pk %}" method="post" enctype="multipart/form-data">
    {%csrf_token%} {{form.as_p}}
    <button class="btn btn-primary">수정 완료</button>
  </form>
</div>
{%endblock%}

SWIDEA_SITE/templates/ideas/ideas_list.html
{% extends 'base.html' %}
{% load static %}


{%block header%}
    <h2>아이디어 관리</h2>
    <p>당신의 아이디어를 관리하세요</p>
    <form method="post" action="{% url 'ideas:list' %}">
        {% csrf_token %}
        <label for="sort-option">정렬 기준:</label>
        <select id="sort-option" name="sort_option">
            <option value="" selected disabled hidden>--------</option>
            <option value="title">이름 순</option>
            <option value="-id">최신 순</option>
            <option value="id">등록 순</option>
            <option value="-interest">관심도 순</option>
        </select>
        <button type="submit">Sort</button>
    </form>
{%endblock%}

{%block content%}
    <div class = "idea_list">    
        {% for idea in ideas %}
            <div class = "list_li">
                {% if idea.image.url != NULL and idea.image.url != '' %}
                    <img src = "{{idea.image.url}}" alt = "대체 텍스트">
                {% else %}
                    <img src = "{% static 'ideas/image/no_img.png' %}" alt = "대체 텍스트">
                {% endif %}
                <div class = 'info'>
                    <a href = "{% url 'ideas:detail' idea.pk%}" class="title">{{idea.title}}</a>
                    <p class = "idea_kind">개발 툴 :{{idea.devtool}}</p>
                    <p class = "idea_interest">관심도 : {{idea.interest}}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{%endblock%}